name: Build packages for Windows

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build_windows_packages:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update --init --recursive

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build --target install

      - name: Package
        run: |
          $pkg_name="nanomq-$(git describe --abbrev=0 --tags)-windows-x86_64.zip"
          Compress-Archive -Path install/* -DestinationPath $pkg_name
          mv $pkg_name ./install/ 

      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: "install/*.zip"

      - uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ github.token }}
          file: install/nanomq*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: update nanomq.io
        if: github.event_name == 'release'
        run: |
          try {
            $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
            $headers.Add("token", "${{ secrets.EMQX_IO_TOKEN }}")
            $headers.Add("Content-Type", "application/json")
            $body = "{`"repo`": `"emqx/nanomq`", `"tag`": `"${{ github.ref_name }}`"}"
            $response = Invoke-WebRequest ${{ secrets.EMQX_IO_RELEASE_API }} -Method 'POST' -Headers $headers -Body $body
            if ($response.StatusCode -eq 200) {
              Write-Host "HTTP status code: $($response.StatusCode)"
              Write-Host "Success"
            } else {
              Write-Host "HTTP status code: $($response.StatusCode)"
              Write-Host "Response: $($response.Content)"
              exit 1
            }
          } catch {
            Write-Host "An error occurred: $($_.Exception.Message)"
            exit 1
          }
